### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by huan-robotics** [9woods123/uav_pursuit_evasion#1]
May I ask if there are any papers that can be referenced? Thanks!

**Comment by 9woods123** [comment]
Hello，you can read some papers which study LOS(line of sight) navigation and  Multi Pursuit Multi Evasion based on Apollonius Allocation.

**Comment by huan-robotics** [comment]
> Hello，you can read some papers which study LOS(line of sight) navigation and Multi Pursuit Multi Evasion based on Apollonius Allocation.

Thanks for your suggestion!
